///////////////////////////////////////////////////////////
//  Alumno.cs
//  Implementation of the Class Alumno
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:19:30
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

public class Alumno : Persona {

	private string emailAlumno;

	private TipoAlumno TipoAlumno;

	public Alumno(){

	}

}//end Alumno

