///////////////////////////////////////////////////////////
//  Aula.cs
//  Implementation of the Class Aula
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:38:40
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Aula {

	private int numero;

	public Aula(){

	}

	~Aula(){

	}

}//end Aula