///////////////////////////////////////////////////////////
//  Curso.cs
//  Implementation of the Class Curso
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:19:29
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using RepasoClase4.DomainModel.Academia;

public class Curso
{
    private int Codigo;

    private string Nombre;

    private Aula aula;
    public Aula Aula { 
        get
        {
            return aula;
        }
        set
        {
            //Si alguien cambia el aula asignada a mi curso...voy a notificarlo por email
            if(aula != value)
            {
                aula = value;
                //Acá vamos a utilizar el servicio enviador de email (Relacion de uso <use>)
                new EmailSender().Send("gastonweingand@gmail.com", "gaston.weingand@uai.edu.ar", "Cambiando de aula", "");
            }
        }
    } //Así queda para una agregación...

    public List<Profesor> m_Profesor = new List<Profesor>(); //Composición

    public List<Alumno> m_Alumno = new List<Alumno>(); //Composición

    /// <summary>
    /// En la composición, solicito en el contructor de la clase que es compuesta todas las instancias necesarias para existir
    /// </summary>
    /// <param name="listaProfesores"></param>
    /// <param name="listaAlumnos"></param>
    public Curso(List<Profesor> listaProfesores, List<Alumno> listaAlumnos)
    {
        this.m_Profesor = listaProfesores;

        this.m_Alumno = listaAlumnos;
    }



}//end Curso