///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:19:32
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Persona {

	private DateTime FechaNac;
	private string Nombre;

	public Persona(){

	}

}//end Persona