///////////////////////////////////////////////////////////
//  Profesor.cs
//  Implementation of the Class Profesor
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:19:31
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Profesor : Persona {

	private int Legajo;

	public Profesor(){

	}


}//end Profesor