///////////////////////////////////////////////////////////
//  TipoAlumno.cs
//  Implementation of the Enumeration TipoAlumno
//  Generated by Enterprise Architect
//  Created on:      04-nov.-2023 12:24:59
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum TipoAlumno : int {

	Estudioso,
	NoEstudioso,
	Intermitente,
	OtroTipo

}